#!/bin/bash

script_dir=$(dirname "$(readlink -f "$0")")

bcd=$(pwd)

cd af_run
export ALPHAFOLD_MULTIMER_PATH=PATHTOALPHAFOLDDIR
export ALPHAFOLD_PARAMS_PATH=PATHTOPARAMSDIR
PATHTOENVDIR/bin/python $script_dir/af2_wrapper/run_af2.py job.json &> FUN
mkdir fet
mv feature* fet/

cd $bcd

mkdir IPSAE
cd IPSAE
opdb=$(ls ../af_run/*.pdb)
ojs=$(ls ../af_run/*metrics.json)
python $script_dir/IPSAE/ipsae.py $ojs $opdb 15 15 

cd $bcd
mkdir aftest
cd aftest 
python $script_dir/assess_pik.py --target-dir ${bcd}/af_run --input-json ${bcd}/af_run/job.json

